### ISSUE TITLE
I tested the model(model_0070.tar) in the code , but it didn't work well

### ISSUE THREAD

**Issue by huangjun0413** [Taltt/FNSE-SAT#2]
![image](https://github.com/user-attachments/assets/3c27ab19-31c0-4747-8564-070480a4620d)

**Comment by huangjun0413** [comment]
hello，I tested the model(model_0070.tar) in the code , but it didn't work well. Can you tell me where the problem is

**Comment by Taltt** [comment]
This is fine on my server. You can try setting strict=True in in model.load_state_dict(). 
Otherwise it's a problem with the version of the environment library. My torch is 1.9.0.

**Comment by huangjun0413** [comment]
Setting strict=True solved my problem，Thank you.
